#ifndef __CMATH_CALL_H__
#define __CMATH_CALL_H__

#include "cmath/cglm.h"
#include "cmath/call/vec2.h"
#include "cmath/call/vec3.h"
#include "cmath/call/vec4.h"
#include "cmath/call/ivec2.h"
#include "cmath/call/ivec3.h"
#include "cmath/call/ivec4.h"
#include "cmath/call/mat2.h"
#include "cmath/call/mat3.h"
#include "cmath/call/mat4.h"
#include "cmath/call/affine.h"
#include "cmath/call/cam.h"
#include "cmath/call/quat.h"
#include "cmath/call/euler.h"
#include "cmath/call/plane.h"
#include "cmath/call/frustum.h"
#include "cmath/call/box.h"
#include "cmath/call/io.h"
#include "cmath/call/project.h"
#include "cmath/call/sphere.h"
#include "cmath/call/ease.h"
#include "cmath/call/curve.h"
#include "cmath/call/bezier.h"
#include "cmath/call/ray.h"
#include "cmath/call/affine2d.h"

#endif /* cglm_call_h */
